<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>True</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
    <None Include="paket.references" />
    <None Include="bun_zipper.ply" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Aardvark.PolyMesh.Csg\Aardvark.PolyMesh.Csg.csproj" />
    <ProjectReference Include="..\..\Aardvark.Geometry.PolyMesh\Aardvark.Geometry.PolyMesh.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
